# Intervalos de Confianza y Muestreo

In [1]:
# importar las librerías necesarías.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as st

In [2]:
# leer el dataframe

df = pd.read_csv('Spotify31.csv')

In [3]:
df

duration_min  year  popularity  danceability  energy  loudness  mode  \
0             3.31  2000          86         0.751   0.834    -5.444     0   
1             2.47  1999          88         0.434   0.897    -4.918     1   
2             2.47  1999          88         0.434   0.897    -4.918     1   
3             4.11  1999          74         0.529   0.496    -9.007     1   
4             4.11  1999          74         0.529   0.496    -9.007     1   
...            ...   ...         ...           ...     ...       ...   ...   
3674          2.58  2019          87         0.552   0.702    -5.707     1   
3675          3.21  2019          77         0.847   0.678    -8.635     1   
3676          3.21  2019          77         0.847   0.678    -8.635     1   
3677          2.51  2019          84         0.741   0.520    -7.513     1   
3678          3.35  2019          95         0.695   0.762    -3.497     1   

      speechiness  liveness  valence    tempo  Generos   period  
0          0.0437    0.3550    0.894   95.053      Pop  1-98/04  
1          0.0488    0.6120    0.684  148.726      Pop  1-98/04  
2          0.0488    0.6120    0.684  148.726     Rock  1-98/04  
3          0.0290    0.2510    0.278  136.859      Pop  1-98/04  
4          0.0290    0.2510    0.278  136.859  Country  1-98/04  
...           ...       ...      ...      ...      ...      ...  
3674       0.1570    0.1050    0.564  169.994      Pop  4-16/20  
3675       0.1090    0.2740    0.811   97.984  Country  4-16/20  
3676       0.1090    0.2740    0.811   97.984  Hip-Hop  4-16/20  
3677       0.0656    0.2220    0.347  102.998      Pop  4-16/20  
3678       0.0395    0.0863    0.553  120.042  Hip-Hop  4-16/20  

[3679 rows x 13 columns]

In [4]:
df.head()

duration_min  year  popularity  danceability  energy  loudness  mode  \
0          3.31  2000          86         0.751   0.834    -5.444     0   
1          2.47  1999          88         0.434   0.897    -4.918     1   
2          2.47  1999          88         0.434   0.897    -4.918     1   
3          4.11  1999          74         0.529   0.496    -9.007     1   
4          4.11  1999          74         0.529   0.496    -9.007     1   

   speechiness  liveness  valence    tempo  Generos   period  
0       0.0437     0.355    0.894   95.053      Pop  1-98/04  
1       0.0488     0.612    0.684  148.726      Pop  1-98/04  
2       0.0488     0.612    0.684  148.726     Rock  1-98/04  
3       0.0290     0.251    0.278  136.859      Pop  1-98/04  
4       0.0290     0.251    0.278  136.859  Country  1-98/04

In [7]:
df.columns

Index(['duration_min', 'year', 'popularity', 'danceability', 'energy',
       'loudness', 'mode', 'speechiness', 'liveness', 'valence', 'tempo',
       'Generos', 'period'],
      dtype='object')

In [8]:
# obtener los nombre de las variables a usar.

names = ['duration_min', 'year', 'popularity', 'danceability', 'energy',
       'loudness', 'mode', 'speechiness', 'liveness', 'valence', 'tempo']

In [9]:
# calcular la media del dataframe original.

df_mean = list(df[names].mean())

In [10]:
df_mean

[3.623452025006795,
 2009.3419407447675,
 66.6273443870617,
 0.6717254688774122,
 0.7186327806469149,
 -5.505134819244359,
 0.5485186191899973,
 0.10657284588203317,
 0.18115819516172874,
 0.5536269094862735,
 119.7410078825768]

# Muestreo

### Muestreo de tamaño 10

In [11]:
mues1_10 = df.sample(10, random_state = 42)
mues2_10 = df.sample(10, random_state = 42)
mues3_10 = df.sample(10, random_state = 42)
mues4_10 = df.sample(10, random_state = 42)
mues5_10 = df.sample(10, random_state = 42)

### Muestreo de tamaño 30

In [12]:
mues1_30 = df.sample(30, random_state = 42)
mues2_30 = df.sample(30, random_state = 42)
mues3_30 = df.sample(30, random_state = 42)
mues4_30 = df.sample(30, random_state = 42)
mues5_30 = df.sample(30, random_state = 42)

### Muestreo de tamaño 50

In [13]:
mues1_50 = df.sample(50, random_state = 42)
mues2_50 = df.sample(50, random_state = 42)
mues3_50 = df.sample(50, random_state = 42)
mues4_50 = df.sample(50, random_state = 42)
mues5_50 = df.sample(50, random_state = 42)

### Muestreo de tamaño 100

In [14]:
mues1_100 = df.sample(100, random_state = 42)
mues2_100 = df.sample(100, random_state = 42)
mues3_100 = df.sample(100, random_state = 42)
mues4_100 = df.sample(100, random_state = 42)
mues5_100 = df.sample(100, random_state = 42)

### Muestreo de tamaño 500

In [15]:
mues1_500 = df.sample(500, random_state = 42)
mues2_500 = df.sample(500, random_state = 42)
mues3_500 = df.sample(500, random_state = 42)
mues4_500 = df.sample(500, random_state = 42)
mues5_500 = df.sample(500, random_state = 42)

### Muestreo de tamaño 1000

In [16]:
mues1_1000 = df.sample(1000, random_state = 42)
mues2_1000 = df.sample(1000, random_state = 42)
mues3_1000 = df.sample(1000, random_state = 42)
mues4_1000 = df.sample(1000, random_state = 42)
mues5_1000 = df.sample(1000, random_state = 42)

In [17]:
# crear una lista con las muestras obtenidas.

muestras = [mues1_10,   mues2_10,   mues3_10,   mues4_10,   mues5_10,
            mues1_30,   mues2_30,   mues3_30,   mues4_30,   mues5_30,
            mues1_50,   mues2_50,   mues3_50,   mues4_50,   mues5_50,
            mues1_100,  mues2_100,  mues3_100,  mues4_100,  mues5_100,
            mues1_500,  mues2_500,  mues3_500,  mues4_500,  mues5_500,
            mues1_1000, mues2_1000, mues3_1000, mues4_1000, mues5_1000]

In [18]:
# calcular la media de cada una de las variables en las muestras.

medias = [np.array(f[names].mean()) for f in muestras]
medias

[array([ 3.841000e+00,  2.008900e+03,  6.750000e+01,  6.334000e-01,
         6.753000e-01, -6.434000e+00,  7.000000e-01,  1.255400e-01,
         2.223500e-01,  4.958000e-01,  1.250618e+02]),
 array([ 3.841000e+00,  2.008900e+03,  6.750000e+01,  6.334000e-01,
         6.753000e-01, -6.434000e+00,  7.000000e-01,  1.255400e-01,
         2.223500e-01,  4.958000e-01,  1.250618e+02]),
 array([ 3.841000e+00,  2.008900e+03,  6.750000e+01,  6.334000e-01,
         6.753000e-01, -6.434000e+00,  7.000000e-01,  1.255400e-01,
         2.223500e-01,  4.958000e-01,  1.250618e+02]),
 array([ 3.841000e+00,  2.008900e+03,  6.750000e+01,  6.334000e-01,
         6.753000e-01, -6.434000e+00,  7.000000e-01,  1.255400e-01,
         2.223500e-01,  4.958000e-01,  1.250618e+02]),
 array([ 3.841000e+00,  2.008900e+03,  6.750000e+01,  6.334000e-01,
         6.753000e-01, -6.434000e+00,  7.000000e-01,  1.255400e-01,
         2.223500e-01,  4.958000e-01,  1.250618e+02]),
 array([ 3.63633333e+00,  2.00856667e+03,  6.

In [19]:
medias2 = [np.array([medias[0][i],
                     medias[1][i],
                     medias[2][i],
                     medias[3][i],
                     medias[4][i],
                     medias[5][i],
                     medias[6][i],
                     medias[7][i],
                     medias[8][i]]) for i in range(8)]

In [20]:
mediaMedias = [m.mean() for m in medias2]
mediaMedias

[3.7500370370370373,
 2008.7518518518518,
 68.35925925925926,
 0.6465555555555556,
 0.6763074074074074,
 -6.239644444444443,
 0.6703703703703704,
 0.11966]

In [21]:
for i in range(8):
    print(f"La diferencia entre la media original y la media de medias de la variable {names[i]} es: {abs(df_mean[i] - mediaMedias[i])}")

La diferencia entre la media original y la media de medias de la variable duration_min es: 0.12658501203024208
La diferencia entre la media original y la media de medias de la variable year es: 0.5900888929156736
La diferencia entre la media original y la media de medias de la variable popularity es: 1.7319148721975637
La diferencia entre la media original y la media de medias de la variable danceability es: 0.025169913321856696
La diferencia entre la media original y la media de medias de la variable energy es: 0.04232537323950758
La diferencia entre la media original y la media de medias de la variable loudness es: 0.7345096252000838
La diferencia entre la media original y la media de medias de la variable mode es: 0.12185175118037306
La diferencia entre la media original y la media de medias de la variable speechiness es: 0.013087154117966834


## Intervalos de Confianza

In [22]:
import scipy.stats as stats
from scipy.stats import norm

In [23]:
# Error Estándar

def ErrorEstandar(x):
    return x.std() / np.sqrt(len(x))

In [24]:
# Intervalos de Confianza

def IntervaloConfianza(x, li, ls):
    return x.mean() + (norm.ppf(li)) * ErrorEstandar(x) , x.mean() + (norm.ppf(ls)) * ErrorEstandar(x)

## duration_min

In [25]:
df['duration_min'].mean()

3.623452025006795

#### Con .025 y .975

In [26]:
print(IntervaloConfianza(mues1_10['duration_min'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['duration_min'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['duration_min'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['duration_min'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['duration_min'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['duration_min'], 0.025, 0.975))

(3.1678225095315717, 4.514177490468429)
(3.367950948744208, 3.9047157179224596)
(3.357283088714876, 3.788716911285124)
(3.4492145560696628, 3.751785443930336)
(3.5411783246728636, 3.6536616753271365)
(3.577760605578287, 3.6568993944217127)


### Con .005, .995

In [27]:
print(IntervaloConfianza(mues1_10['duration_min'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['duration_min'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['duration_min'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['duration_min'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['duration_min'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['duration_min'],0.005, 0.995))

(2.956294811478383, 4.7257051885216175)
(3.283619091523819, 3.9890475751428487)
(3.2894999225791, 3.8565000774209)
(3.4016772243010815, 3.799322775698917)
(3.523505909470261, 3.671334090529739)
(3.5653270007208824, 3.6693329992791175)


## year

In [28]:
df['year'].mean()

2009.3419407447675

#### Con .025 y .975

In [29]:
print(IntervaloConfianza(mues1_10['year'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['year'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['year'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['year'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['year'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['year'], 0.025, 0.975))

(2005.3401480619677, 2012.4598519380324)
(2006.5300652697217, 2010.6032680636115)
(2007.7321737811433, 2011.027826218857)
(2007.6627947970053, 2010.0172052029945)
(2008.3756418756805, 2009.4323581243195)
(2008.691502291015, 2009.420497708985)


#### Con .005, .995

In [30]:
print(IntervaloConfianza(mues1_10['year'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['year'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['year'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['year'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['year'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['year'],0.005, 0.995))

(2004.221561513065, 2013.5784384869353)
(2005.89011873044, 2011.2432146028932)
(2007.214389256554, 2011.545610743446)
(2007.292890113246, 2010.387109886754)
(2008.2096197205021, 2009.5983802794979)
(2008.5769688099958, 2009.5350311900042)


## popularity

In [31]:
df['popularity'].mean()

66.6273443870617

#### Con .025 y .975

In [32]:
print(IntervaloConfianza(mues1_10['popularity'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['popularity'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['popularity'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['popularity'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['popularity'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['popularity'], 0.025, 0.975))

(51.61676552681601, 83.38323447318399)
(61.69569961884112, 77.17096704782556)
(57.41475447791805, 72.02524552208195)
(61.4824629336164, 70.71753706638358)
(64.72587072867064, 68.67812927132935)
(65.34723013126758, 68.22476986873242)


#### Con .005, .995

In [33]:
print(IntervaloConfianza(mues1_10['popularity'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['popularity'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['popularity'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['popularity'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['popularity'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['popularity'],0.005, 0.995))

(46.62589153990686, 88.37410846009314)
(59.26435889343098, 79.6023077732357)
(55.119279969517464, 74.32072003048253)
(60.0315276302869, 72.16847236971309)
(64.10492590841388, 69.29907409158612)
(64.89513587281355, 68.67686412718645)


## danceability

In [34]:
df['danceability'].mean()

0.6717254688774122

In [35]:
print(IntervaloConfianza(mues1_10['danceability'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['danceability'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['danceability'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['danceability'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['danceability'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['danceability'], 0.025, 0.975))

(0.5214304826666167, 0.7453695173333832)
(0.6056613257010084, 0.7203386742989917)
(0.6201945217751111, 0.7133254782248887)
(0.6355316272322009, 0.6974283727677988)
(0.655604049426735, 0.680979950573265)
(0.6645215672954992, 0.6823344327045009)


## energy

In [36]:
df['energy'].mean()

0.7186327806469149

#### Con .025 y .975

In [37]:
print(IntervaloConfianza(mues1_10['energy'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['energy'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['energy'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['energy'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['energy'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['energy'], 0.025, 0.975))

(0.5713672537619816, 0.7792327462380183)
(0.6243845711402072, 0.7307487621931259)
(0.6330226207889779, 0.720977379211022)
(0.682964788409366, 0.7407952115906341)
(0.7011869356718372, 0.7279086643281627)
(0.7106144428517399, 0.7290013571482602)


#### Con .005, .995

In [38]:
print(IntervaloConfianza(mues1_10['energy'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['energy'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['energy'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['energy'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['energy'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['energy'],0.005, 0.995))

(0.5387092179907971, 0.811890782009203)
(0.6076735455880473, 0.7474597877452858)
(0.619203926725921, 0.7347960732740789)
(0.6738789704295763, 0.7498810295704238)
(0.6969886478274671, 0.7321069521725329)
(0.7077256492493736, 0.7318901507506265)


## loudness

In [39]:
df['loudness'].mean()

-5.505134819244359

#### Con .025 y .975

In [40]:
print(IntervaloConfianza(mues1_10['loudness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['loudness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['loudness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['loudness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['loudness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['loudness'], 0.025, 0.975))

(-7.608413261640653, -5.259586738359347)
(-6.624393998000238, -5.369006001999762)
(-6.502525723872164, -5.413754276127838)
(-5.965051241806106, -5.243808758193895)
(-5.749582197772237, -5.401501802227762)
(-5.610895041318292, -5.3745129586817075)


#### Con .005, .995

In [41]:
print(IntervaloConfianza(mues1_10['loudness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['loudness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['loudness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['loudness'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['loudness'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['loudness'],0.005, 0.995))

(-7.977440653844633, -4.890559346155365)
(-6.82162974690563, -5.171770253094369)
(-6.673584115832907, -5.242695884167095)
(-6.078366648557522, -5.130493351442478)
(-5.804269591401317, -5.346814408598682)
(-5.64803335811372, -5.33737464188628)


## mode

In [ ]:
df['mode'].mean()

0.5486148832156437

#### Con .025 y .975

In [42]:
print(IntervaloConfianza(mues1_10['mode'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['mode'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['mode'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['mode'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['mode'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['mode'], 0.025, 0.975))

(0.4006105560485981, 0.9993894439514017)
(0.45794488721554605, 0.8087217794511206)
(0.48409429303061746, 0.7559057069693825)
(0.46221981705913096, 0.6577801829408692)
(0.5083678750724179, 0.5956321249275822)
(0.5131150275632455, 0.5748849724367545)


#### Con .005, .995

In [43]:
print(IntervaloConfianza(mues1_10['mode'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['mode'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['mode'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['mode'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['mode'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['mode'],0.005, 0.995))

(0.3065355746400593, 1.0934644253599406)
(0.40283384325208005, 0.8638328234145864)
(0.4413896248642463, 0.7986103751357536)
(0.4314950567907664, 0.6885049432092336)
(0.49465766776783554, 0.6093423322321645)
(0.5034102658674305, 0.5845897341325695)


## speechiness

In [ ]:
df['speechiness'].mean()

0.1065175719717545

#### Con .025 y .975

In [45]:
print(IntervaloConfianza(mues1_10['speechiness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['speechiness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['speechiness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['speechiness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['speechiness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['speechiness'], 0.025, 0.975))

(0.05110674698147698, 0.19997325301852298)
(0.07624268206400751, 0.1483773179359925)
(0.0889436708247164, 0.1478443291752836)
(0.08870522522169245, 0.1272987747783076)
(0.09295706584215854, 0.10886933415784146)
(0.10177284861228764, 0.11364375138771238)


#### Con .005, .995

In [ ]:
print(IntervaloConfianza(mues1_10['speechiness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['speechiness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['speechiness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['speechiness'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['speechiness'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['speechiness'],0.005, 0.995))

(0.028906161725148552, 0.12501383827485144)
(0.05181561112191127, 0.13709105554475542)
(0.06169865826785939, 0.12328534173214062)
(0.07818788242467059, 0.12199011757532943)
(0.091602676034829, 0.11244972396517097)
(0.09434691030478862, 0.10886028969521139)


## liveness

In [44]:
df['liveness'].mean()

0.18115819516172874

#### Con .025 y .975

In [46]:
print(IntervaloConfianza(mues1_10['liveness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['liveness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['liveness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['liveness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['liveness'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['liveness'], 0.025, 0.975))

(0.07517510141522843, 0.36952489858477156)
(0.1346996318447825, 0.2638137014885509)
(0.14341029157493773, 0.23459770842506225)
(0.16089849904609435, 0.22263950095390564)
(0.16969906717054054, 0.19479173282945952)
(0.17313379660895167, 0.19119920339104834)


#### Con .005, .995

In [47]:
print(IntervaloConfianza(mues1_10['liveness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['liveness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['liveness'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['liveness'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['liveness'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['liveness'],0.005, 0.995))

(0.02892939660536406, 0.4157706033946359)
(0.11441434131982677, 0.28409899201350663)
(0.12908371006349903, 0.24892428993650095)
(0.1511982846197555, 0.23233971538024448)
(0.16575672367272393, 0.19873407632727613)
(0.17029551549801294, 0.19403748450198707)


## valence

In [ ]:
df['valence'].mean()

0.5533697447039653

#### Con .025 y .975

In [ ]:
print(IntervaloConfianza(mues1_10['valence'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['valence'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['valence'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['valence'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['valence'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['valence'], 0.025, 0.975))

(0.439128443325006, 0.6870715566749941)
(0.4918095527684498, 0.6323237805648834)
(0.5014442623663236, 0.6168357376336764)
(0.5428338433239264, 0.6239861566760738)
(0.5458794002001148, 0.584211399799885)
(0.5447218108019771, 0.572330189198023)


#### Con .005, .995

In [ ]:
print(IntervaloConfianza(mues1_10['valence'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['valence'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['valence'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['valence'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['valence'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['valence'],0.005, 0.995))

(0.4001737569624474, 0.7260262430375527)
(0.4697331675874639, 0.6544001657458693)
(0.48331494767304706, 0.6349650523269529)
(0.5300838908387906, 0.6367361091612096)
(0.5398570065877905, 0.5902337934122094)
(0.5403842201874772, 0.5766677798125229)


## Tempo

In [ ]:
df['tempo'].mean()

119.7226588810429

#### Con .025 y .975

In [ ]:
print(IntervaloConfianza(mues1_10['tempo'], 0.025, 0.975))
print(IntervaloConfianza(mues1_30['tempo'], 0.025, 0.975))
print(IntervaloConfianza(mues1_50['tempo'], 0.025, 0.975))
print(IntervaloConfianza(mues1_100['tempo'], 0.025, 0.975))
print(IntervaloConfianza(mues1_500['tempo'], 0.025, 0.975))
print(IntervaloConfianza(mues1_1000['tempo'], 0.025, 0.975))

(93.30492089037088, 122.64587910962913)
(110.92932091306918, 130.2637457535975)
(115.4683852434519, 129.57089475654814)
(114.10551347483207, 124.49238652516792)
(118.01603661245225, 122.80861138754777)
(117.44924962725575, 120.79068837274427)


#### Con .005, .995

In [ ]:
print(IntervaloConfianza(mues1_10['tempo'], 0.005, 0.995))
print(IntervaloConfianza(mues1_30['tempo'], 0.005, 0.995))
print(IntervaloConfianza(mues1_50['tempo'], 0.005, 0.995))
print(IntervaloConfianza(mues1_100['tempo'],0.005, 0.995))
print(IntervaloConfianza(mues1_500['tempo'],0.005, 0.995))
print(IntervaloConfianza(mues1_1000['tempo'],0.005, 0.995))

(88.69512225726763, 127.25567774273239)
(107.8916626152156, 133.30140405145107)
(113.25272041781827, 131.78655958218178)
(112.47361744635717, 126.12428255364281)
(117.26306854364597, 123.56157945635405)
(116.92427155235971, 121.31566644764031)
